
library(shiny)
if (!require("DT")) install.packages('DT')
library(DT)
library(DECM)

navbarPage(title = 'Climate model data explorer (Beta version)', 
           id = 'x0',
           header=img(src="banner_c3s.png", 
                      style="width:700px; float:left; margin-bottom:50px; margin-left:20px"),
           tabPanel('Browse', 
                    dataTableOutput('glossary'),                    
                    h3(textOutput('text')),
                    DT::dataTableOutput("table")
                    #plotOutput("plot")
           ),
           tabPanel('Map of climate change', 
                    column(3,
		         selectInput("type",
                           label = "What to show on map",
                           choices = c("Climate change near future",
                                       "Climate change far future",
                                       "Mean value present day",
                                       "Mean value near future",
                                       "Mean value far future"),
                           selected = "Climate change far future"),
                         selectInput("varid",
                           label = "Climate variable",
                           choices = c("Temperature",
                                       "Precipitation"),
                           selected = "Temperature")),
		                column(3,
                    plotOutput("map"))
           ),
           tabPanel('Scatterplot of climate change', 
                    #textInput('x2', 'Row ID'), 
                    plotOutput("dtdpr")
           )#,
           #tabPanel('View data', 
           #         #textInput('x2', 'Row ID'), 
           #         DT::dataTableOutput("selsta",width = 'auto'),
           #         DT::dataTableOutput("rawdata",width = 'auto')
           #),
           #tabPanel('Download', 
           #         #textInput('x2', 'Row ID'), 
           #         downloadLink('downloadMeta', 'Download Meta'),
           #         downloadLink('downloadData', 'Download Data') 
           #)
)

# Define the overall UI
# navbarPage(title = 'GCM explorer (Beta version)', 
#            id = 'x0',
#            tabPanel('Browse', 
#                     h4(textOutput('text')),
#                     h3(textOutput('text1')),
#                     dataTableOutput('varnames'),
#                     h3(textOutput('text2')),
#                     DT::dataTableOutput("table")
#                     #plotOutput("plot")
#            ),
#            tabPanel('Map', 
#                     #textInput('x2', 'Row ID'), 
#                     plotOutput("map")
#            ),
#            tabPanel('Locate', 
#                     #textInput('x2', 'Row ID'), 
#                     plotOutput("map")#,width = "auto", height = "auto")
#            ),
#            tabPanel('Download', 
#                     #textInput('x2', 'Row ID'), 
#                     downloadLink('downloadMeta', 'Download Meta'),
#                     downloadLink('downloadData', 'Download Data') 
#            )
# )
# 

#cmnames <<- names(Z4[[1]])[-c(1,2)]
# 
# navbarPage("Prototype CDS-tool",
#     tabPanel("Maps",
#              column(3,
#                     selectInput("param1",
#                                 label = "Element",
#                                 choices = c("Temperature","Precip. sum",
#                                             "Wet-day freq.","Precip. intensity"),
#                                 selected = "Temperature")),
#              column(2,
#                     selectInput("season1",
#                                 label = "Season",
#                                 choices = c("Winter", "Spring","Summer","Autumn"),
#                                 selected = "Winter")),
#              column(3,
#                     sliderInput("lon1",
#                                 label = "Longitudes",
#                                 min = 0, max = 30, value = c(0, 30))),
#              column(3,
#                     sliderInput("lat1",
#                                 label = "Latitudes",
#                                 min = 55, max = 72, value = c(55, 72))),
#              column(3,
#                     sliderInput("dates1", "Years",
#                                 min=1900, max=2099, value= c(2050,2050),sep="")),
#              column(2,
#                     selectInput("rcp1",
#                                 label = "Scenario",
#                                 choices = c("RCP4.5","RCP2.6", "RCP8.5"),
#                                 selected = "RCP4.5")),
#              plotOutput("maps")
#              ),
# tabPanel("Single model",  ## Unfinished!
#          column(3,
#                 selectInput("im7",
#                             label = "Model",
#                             choices = gcmnames,
#                             selected = gcmnames[1])),
#          column(3,
#                 selectInput("param7",
#                             label = "Element",
#                             choices = c("Temperature","Wet-day freq.",
#                                         "Precip. intensity"),
#                             selected = "Temperature")),
#          column(2,
#                 selectInput("season7",
#                             label = "Season",
#                             choices = c("Winter", "Spring","Summer","Autumn"),
#                             selected = "Winter")),
#          column(2,
#                 selectInput("rcp7",
#                             label = "Scenario",
#                             choices = c("RCP4.5","RCP2.6", "RCP8.5"),
#                             selected = "RCP4.5")),
#          column(3,
#                 sliderInput("lon7",
#                             label = "Longitudes",
#                             min = 0, max = 30, value = c(0, 30))),
#          column(3,
#                 sliderInput("lat7",
#                             label = "Latitudes",
#                             min = 55, max = 72, value = c(55, 72))),
#          column(3,
#                 sliderInput("dates7",
#                             "Years",
#                             min=1900, max=2099, value= c(2045,2055),sep="")),
#          plotOutput("plot1model")),
# 
# tabPanel("Quality",  ## Unfinished!
#              column(2,
#                     selectInput("param6",
#                                 label = "Element",
#                                 choices = c("Temperature","Wet-day freq.",
#                                             "Precip. intensity"),
#                                 selected = "Temperature")),
#              column(2,
#                     selectInput("quality6",
#                                 label = "Evaluation",
#                                 choices = c("trend","spread"),
#                                 selected = "RCP4.5")),
#              column(2,
#                     selectInput("season6",
#                                 label = "Season",
#                                 choices = c("Winter", "Spring","Summer","Autumn"),
#                                 selected = "Winter")),
#              column(2,
#                     selectInput("rcp6",
#                                 label = "Scenario",
#                                 choices = c("RCP4.5","RCP2.6", "RCP8.5"),
#                                 selected = "RCP4.5")),
#              column(3,
#                     sliderInput("lon6",
#                                 label = "Longitudes",
#                                 min = 0, max = 30, value = c(0, 30))),
#              column(3,
#                     sliderInput("lat6",
#                                 label = "Latitudes",
#                                 min = 55, max = 72, value = c(55, 72))),
#             plotOutput("map.quality")
#     ),
#     tabPanel("Settings", ## Unfinished! Aslo include settings for maps: text
#              column(2,
#                     selectInput("aspect",
#                                 label = "Aspect",
#                                 choices = c("Mean value", "Change","Trend","Variability"),
#                                 selected = "Mean value")),
#              column(3,
#                     selectInput("stats",
#                                 label = "Statistic",
#                                 choices = c("Ensemble mean", "Ensemble spread"),
#                                 selected = "Ensemble mean")),
#              column(3,
#                     sliderInput("baseline", "Years",
#                                 min=1900, max=2099, value= c(1961,1990),sep="")),
#              column(2,
#                     checkboxGroupInput("im",
#                                        label = "Model run",
#                                        choices = gcmnames,
#                                        selected=gcmnames)),
# 
# 
#              tableOutput("table")),
# 
#     tabPanel("Usage statistics",  ## Unfinished!
#              column(12,
#                     h1("Usage statistics"),
#                     h2("Unfinished"),
#                     "Statistics over which type of information is most sought and counter for number of visits.",
#                     "Such information may be used to help others see what type of information is used the most",
#                     "and can be used as guidance for further development and improvement of tools like this.",
#                     "This page can also include a feedback/comment option for user response.",
#                     "Google analytics may also offer ways to understand how the information is being used and",
#                     "be used for future improvements.")),
#     tabPanel("Disclaimer & info",
#          column(12,
#                 h1("Disclaimer"),
#                 "These results are the best estimated based on current knowledge, but do not account for any unknown",
#                 "or unexpected events or phenomena that may have a consequence for the future climate",
#                 "They are also limited by the degree which the global climate models capture the large-scale",
#                 "conditions and the ability of the downscaling to capture the dependency between large and local scales.",
#                 "This app provides a demonstration of compressing information: the data presented here would require more",
#                 "than X Mb if it were stored uncompressed as 16-bit numbers, whereas the actual space needed is X Mb for compressed",
#                 "R-binary (rda) files. The reduction in data volume is achieved by using EOFs to discard noise and emphasise",
#                 "the signal. The use of EOFs also greatly speed up the data processing.",
#                 h2("Downscaling"),
#                 "For an introduction about downscaling, please see the article on Downscaling Climate Information in",
#                 a("Oxford Research Encyclopedia.",href="http://goo.gl/J5Q2Py"),
#                 h2("Source code"),
#                 a("GitHub",href="https://github.com/metno/abc4cde_wp4"),
#                 "which is based on the R-package 'esd' also available on ",a("GitHub.",href="https://github.com/metno/esd"),
#                 h2("Data"),
#                 "The data (DOI: 10.6084/m9.figshare.2056701.v2) is available from ",
#                 a("GitHub.",href="https://github.com/metno/esd_Rshiny/tree/master/dse4KSS/data"))
#          )
# )
